site_name: Standardized Flowsheet Format (SFF)
site_description: A universally interoperable file format for process designs.
site_url: https://sustainability-software-lab.github.io/pisces-standard-flowsheet-format/
repo_url: https://github.com/sustainability-software-lab/pisces-standard-flowsheet-format
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
  palette:
    primary: indigo

nav:
  - Home: index.md
  - Schema Reference: schema_reference.md

extra_css:
  - stylesheets/extra.css
